### ISSUE TITLE
پینگ سایت های دارای ssl

### ISSUE THREAD

**Issue by bahiraee** [VahidN/DNTScheduler#3]
برای سایت های دارای گواهینامه اس اس ال پینگ برنامه توسط پورت 80 انجام می شود.
چگونه میتوان به طور پیش فرض پینگ برنامه را با پورت 443 اس اس ال انجام داد؟

**Comment by VahidN** [comment]
<div dir="rtl">

اينطور نيست. [ThisApp.SiteRootUrl](https://github.com/VahidN/DNTScheduler/blob/489799fdd20323d46ed5e9a84ac202b5ffd201d6/DNTScheduler/DNTSchedulerModule.cs#L37) بر اساس آدرس درخواست جاري تنظيم مي‌شود. اگر ssl باشد به صورت خودكار به آن تنظيم مي‌شود.
ضمن اينكه بحث اصلي زنده نگه داشتن برنامه است و نه پورت 80 يا 81. بحث اصلي رسيدن درخواست به IIS هست تا برنامه را آنلود نكند. فقط همين.
